---
name: Lintcheck Python

on:
  push:
    branches:
      - main
    paths:
      - "**.py"
  pull_request:
    paths:
      - "**.py"

jobs:
  check_python:
    name: "Check Python linting"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - uses: actions/checkout@v4
    - run: "pip install -q uv && uv pip install --system ruff flake8 flake8-bugbear isort"
    - run: "ruff format --check --diff ."
    - run: "flake8"
    - run: "isort -c --diff nle/"
...
